version: "3"

dotenv:
  - ".env"

tasks:
  up:
    cmds:
      - docker compose up -d --remove-orphans

  down:
    cmds:
      - docker compose down -v

  restart:
    cmds:
      - task: down
      - task: up