name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  validate:
    uses: ./.github/workflows/validate.yaml

  smoke:
    needs: validate
    uses: ./.github/workflows/smoke.yaml

  integration:
    needs: smoke
    if: false
    uses: ./.github/workflows/integration.yaml

  e2e:
    needs: integration
    if: false
    uses: ./.github/workflows/e2e.yaml
